package br.com.api.pain.Pain.dto;

public record ChallengesDTO(
        float controlWardTimeCoverageInRiverOrEnemyHalf,
        int earliestBaron,
        int earliestDragonTakedown,
        int earliestElderDragon,
        int earlyLaningPhaseGoldExpAdvantage,
        int laningPhaseGoldExpAdvantage,
        int junglerKillsEarlyJungle,
        int killsOnLanersEarlyJungleAsJungler,
        float maxCsAdvantageOnLaneOpponent,
        int maxLevelLeadLaneOpponent,
        int takedownsFirst25Minutes,
        float visionScoreAdvantageLaneOpponent,
        int abilityUses,
        int controlWardsPlaced,
        float damagePerMinute,
        float damageTakenOnTeamPercentage,
        int firstTurretKilled,
        float gameLength,
        float goldPerMinute,
        float jungleCsBefore10Minutes,
        float kda,
        float killParticipation,
        int soloKills,
        int stealthWardsPlaced,
        int teamBaronKills,
        float teamDamagePercentage,
        int teamElderDragonKills,
        int teamRiftHeraldKills,
        int turretPlatesTaken,
        int turretTakedowns,
        int unseenRecalls,
        float visionScorePerMinute,
        int wardsGuarded
) {
}
